"""
Grounding & Fact Check Agent — LLM-as-Judge Pattern

Purpose:
  The Resolution Agent generates a draft response using GPT-4o.
  That draft may contain specific claims that cannot be verified
  without checking internal bank systems:
    - "Your refund will be processed in 24 hours"
    - "The amount of Rs 45,000 will be credited"
    - "As per our 30-day return policy"

  This agent acts as a second GPT-4o call that JUDGES the first.
  It returns a grounding_score and a list of specific warnings
  that the human agent must verify before sending.

Why LLM-as-judge (not rule-based):
  Rules cannot catch all unverifiable claims — language is too varied.
  "We will resolve this by end of day" and "expect resolution shortly"
  both make unverifiable time commitments but in different words.
  GPT-4o can identify the intent, not just the pattern.

RBI Compliance role:
  For RBI-reportable complaints, we add a stricter check —
  the draft must not promise outcomes that require RBI approval
  or that conflict with the bank's liability framework.
"""

import json
from openai import OpenAI
from app.core.config import get_settings

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        settings = get_settings()
        _client = OpenAI(api_key=settings.openai_api_key)
    return _client


GROUNDING_SYSTEM = """You are a senior compliance reviewer at an Indian bank.
Your job is to review AI-generated customer service drafts before they are sent.

You check for TWO types of problems:

TYPE 1 — UNVERIFIABLE SPECIFIC CLAIMS:
Claims that require checking internal systems before making:
- Specific refund amounts (e.g., "Rs 45,000 will be credited")
- Specific timelines (e.g., "within 24 hours", "by tomorrow")
- Policy references that may be inaccurate (e.g., "as per our 30-day policy")
- Specific actions the bank will take (e.g., "we will block your card immediately")
- Reference numbers or case IDs the agent has not actually created yet

TYPE 2 — RBI COMPLIANCE VIOLATIONS:
Statements that conflict with RBI guidelines:
- Promising outcomes without investigation (unauthorized transaction cases)
- Admitting liability before investigation is complete
- Making commitments beyond the agent's authority level
- Missing mandatory RBI disclosure language for certain complaint types

You must respond ONLY with this exact JSON format:
{
  "grounding_score": <float 0.0-1.0, where 1.0 = fully grounded, 0.0 = many issues>,
  "overall_assessment": "<SAFE_TO_SEND | VERIFY_BEFORE_SEND | DO_NOT_SEND>",
  "warnings": [
    {
      "type": "<UNVERIFIABLE_CLAIM | RBI_COMPLIANCE | AUTHORITY_EXCEEDED>",
      "claim": "<exact phrase from the draft that is problematic>",
      "issue": "<why this is a problem>",
      "suggestion": "<how the agent should handle this>"
    }
  ],
  "positive_aspects": ["<what the draft does well>"],
  "reasoning": "<2 sentence overall assessment>"
}

If there are no warnings, return an empty warnings array [].
grounding_score formula: start at 1.0, subtract 0.15 per warning."""


def run_grounding_check(
    draft_response: str,
    complaint_text: str,
    is_rbi_reportable: bool,
    compliance_category: str,
) -> dict:
    """
    Run the LLM-as-judge grounding check on the resolution draft.

    Args:
        draft_response:      The draft generated by the Resolution Agent
        complaint_text:      Original complaint (for context)
        is_rbi_reportable:   Whether this is an RBI-regulated case
        compliance_category: The specific RBI category if applicable

    Returns dict with:
        grounding_score:     float 0.0-1.0
        overall_assessment:  SAFE_TO_SEND | VERIFY_BEFORE_SEND | DO_NOT_SEND
        warnings:            List of warning dicts with type, claim, issue, suggestion
        positive_aspects:    What the draft does well
        warning_count:       int
        reasoning:           XAI reasoning string
    """
    client = _get_client()

    # Add RBI context to the user prompt for reportable cases
    rbi_context = ""
    if is_rbi_reportable:
        rbi_context = (
            f"\n⚠️ IMPORTANT: This complaint is categorised as "
            f"{compliance_category} under RBI regulations. "
            f"Apply STRICTER scrutiny. The bank cannot admit liability "
            f"or promise specific outcomes before investigation is complete "
            f"as per RBI Limiting Liability guidelines.\n"
        )

    user_message = (
        f"Review this AI-generated customer service response:\n\n"
        f"CUSTOMER COMPLAINT:\n{complaint_text}\n\n"
        f"AI-GENERATED DRAFT RESPONSE:\n{draft_response}\n"
        f"{rbi_context}\n"
        f"Identify any unverifiable claims or compliance issues. "
        f"Respond ONLY with the JSON object."
    )

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": GROUNDING_SYSTEM},
            {"role": "user", "content": user_message},
        ],
        response_format={"type": "json_object"},
        temperature=0.1,
        max_tokens=600,
    )

    result = json.loads(response.choices[0].message.content)

    grounding_score = float(result.get("grounding_score", 1.0))
    grounding_score = max(0.0, min(1.0, grounding_score))  # clamp 0-1

    warnings = result.get("warnings", [])
    overall = result.get("overall_assessment", "VERIFY_BEFORE_SEND")
    positives = result.get("positive_aspects", [])
    gpt_reasoning = result.get("reasoning", "")

    # Build XAI reasoning string
    if not warnings:
        reasoning = (
            f"Grounding check passed — no unverifiable claims detected.\n"
            f"Grounding score: {grounding_score:.0%}\n"
            f"Assessment: {overall}\n"
            f"Positive aspects: {'; '.join(positives[:3]) if positives else 'N/A'}\n"
            f"GPT-4o reviewer: {gpt_reasoning}"
        )
    else:
        warning_lines = []
        for i, w in enumerate(warnings, 1):
            warning_lines.append(
                f"  Warning {i} [{w.get('type', 'UNKNOWN')}]: "
                f"'{w.get('claim', '')}'\n"
                f"    Issue: {w.get('issue', '')}\n"
                f"    Fix: {w.get('suggestion', '')}"
            )
        reasoning = (
            f"Grounding check found {len(warnings)} issue(s) — "
            f"agent must verify before sending.\n"
            f"Grounding score: {grounding_score:.0%}\n"
            f"Assessment: {overall}\n"
            f"Issues found:\n" + "\n".join(warning_lines) + "\n"
            f"GPT-4o reviewer: {gpt_reasoning}"
        )

    return {
        "grounding_score": grounding_score,
        "overall_assessment": overall,
        "warnings": warnings,
        "positive_aspects": positives,
        "warning_count": len(warnings),
        "reasoning": reasoning,
    }