#!/usr/bin/env bash
# Customer Complaint — local development (run each block in its own terminal)

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=========================================="
echo "Terminal 1 — BACKEND (FastAPI)"
echo "=========================================="
echo "cd \"$ROOT/backend\""
echo ""
echo "# If you use a venv (recommended on Ubuntu/Debian):"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo ""
echo "# Linux: set Tesseract path in backend/.env, e.g."
echo "# TESSERACT_CMD=/usr/bin/tesseract"
echo ""
echo "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "=========================================="
echo "Terminal 2 — FRONTEND (Vite)"
echo "=========================================="
echo "cd \"$ROOT/frontend\""
echo "npm install"
echo "npm run dev"
echo ""
echo "Open the URL Vite prints (usually http://localhost:5173)."
echo "API calls go to /api → proxied to http://localhost:8000 (see vite.config.ts)."
echo ""
echo "frontend/.env must match backend/.env:"
echo "  VITE_API_KEY  ===  API_KEY"
echo ""
echo "Pipeline debug: browser F12 → Console (filter 'Pipeline SSE') and Network → stream"
